# COREAPPWE/Dockerfile

FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

COPY . .

# Exponemos el puerto por defecto de Vite (5173)
EXPOSE 5173

# Importante: Vite debe exponerse a la red de Docker, no solo a localhost
CMD ["npm", "run", "dev", "--", "--host"]